### PR TITLE
fix: Product with no custom option throw error

### LINKED ISSUE #73: Product with no custom option throw error on AddToCart
**Describe the bug**
If a product doesn't contain custom option, clicking on `Add To cart` button throws error.

**Expected behavior**
Product should have added to cart and code shouldn't be run which check for custom option if there are no custom option

**Current Behavior**
Currently in code 
```javascript
Object.keys(selectedCustomOptions).forEach((key) => {
      console.log(selectedCustomOptions[key]);
      customOptions.push({
        optionId: key,
        optionValue: selectedCustomOptions[key],
        extensionAttributes: {},
      });
    })
```

`selectedCustomOptions` is null, so iterating over it, is throwing error

**Steps to Reproduce**
1. Replace store url with `http://13.233.82.59/magento/index.php/` and `access_token` with `          f6a7lmt61uyy2elepkvbwp4q0904beh5`
2. Open App
3. Chose first product in Home Category
4. Select configurable options
5. Click add to cart button

**Screenshots**
ezgif com-video-to-gif

**Smartphone (please complete the following information):**
 - Magento Version: [2.1.0]
 - Device: [Android Emulator Nexus 5X]
 - OS: [PIE]
 - Version [28]

**Additional context**
I really don't know much about custom options so do test at your end too.

### PR DESCRIPTION
**Pull request by alexakasanjeev**
**What does this implement/fix? Explain your changes.**
When adding product to cart which has no custom options, it throws error, as `selectedCustomOptions` is null and iterating over it will throw error

**Does this close any currently open issues?**
close #73

**Any other comments?**
See #73 issue for more detail

**Where has this been tested?**
---------------------------
 - Magento Version: [2.1.0]
 - Device: [Android Emulator Nexus 5X]
 - OS: [PIE]
 - Version [28]

### CODE REVIEW

File: src/components/catalog/Product.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ class Product extends Component {
     });
 
     const customOptions = [];
-    Object.keys(selectedCustomOptions).forEach((key) => {
+    selectedCustomOptions && Object.keys(selectedCustomOptions).forEach((key) => {
```
Comment (alexakasanjeev) [inline src/components/catalog/Product.js]: Added a check, if selectedCustomOptions is null, then don't iterate over it

**Comment by troublediehard** [comment]
@alexakasanjeev :pray:
